ASI.MGC.FS/Controllers/FinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ASI.MGC.FS.Domain;
using ASI.MGC.FS.Model;
using ASI.MGC.FS.Models;
using ASI.MGC.FS.WebCommon;
using ASI.MGC.FS.Domain.Repositories;

namespace ASI.MGC.FS.Controllers
{
    public class FinanceController : Controller
    {
        readonly IUnitOfWork _unitOfWork;
        readonly TimeZoneInfo tzInfo;
        DateTime today;
        public FinanceController()
        {
            _unitOfWork = new UnitOfWork();
            tzInfo = TimeZoneInfo.FindSystemTimeZoneById("Arabian Standard Time");
            today = TimeZoneInfo.ConvertTime(DateTime.Now, tzInfo);
        }
        // GET: Finance
        public ActionResult GlCreation()
        {
            var objGlMaster = new GLMASTER();
            ViewBag.accountsType = CommonModelAccessUtility.GetAccountsType();
            ViewBag.glType = CommonModelAccessUtility.GetGlType();
            ViewBag.balanceType = CommonModelAccessUtility.GetBalanceType();
            ViewBag.Today = today.ToShortDateString();
            return View(objGlMaster);
        }

        [HttpPost]
        public JsonResult SaveGlCreation(FormCollection frm, GLMASTER objGlMaster)
        {
            bool success = false;
            string currentUser = CommonModelAccessUtility.GetCurrentUser(_unitOfWork);
            using (var transaction = _unitOfWork.BeginTransaction())
            {
                try
                {
                    var glCode = (from glDetails in _unitOfWork.Repository<GLMASTER>().Query().Get()
                                  where glDetails.GLCODE_LM.Equals(objGlMaster.GLCODE_LM)
                                  select glDetails).SingleOrDefault();
                    if (glCode != null)
                    {
                        glCode.GLDESCRIPTION_LM = objGlMaster.GLDESCRIPTION_LM;
                        glCode.GTYPE_LM = objGlMaster.GTYPE_LM;
                        glCode.LOCATIONCODE_LM = objGlMaster.LOCATIONCODE_LM;
                        glCode.MAINCODE_LM = objGlMaster.MAINCODE_LM;
                        glCode.NOTES_LM = objGlMaster.NOTES_LM;
                        glCode.SUBCODE_LM = objGlMaster.SUBCODE_LM;
                        _unitOfWork.Repository<GLMASTER>().Update(glCode);
                        _unitOfWork.Save();
                    }
                    else
                    {
                        _unitOfWork.Repository<GLMASTER>().Insert(objGlMaster);
                        _unitOfWork.Save();

                        var objGlTransaction = _unitOfWork.Repository<GLTRANSACTION1>().Create();
                        objGlTransaction.DOCDATE_GLT = today.Date;
                        objGlTransaction.GLDATE_GLT = Convert.ToDateTime(frm["GLDate"]);
                        objGlTransaction.DOCNUMBER_GLT = objGlMaster.GLCODE_LM;
                        objGlTransaction.GLACCODE_GLT = objGlMaster.GLCODE_LM;
                        objGlTransaction.OTHERREF_GLT = objGlMaster.GLCODE_LM;
                        objGlTransaction.VARUSER = currentUser;
                        if (Convert.ToInt32(frm["BalanceType"]) == 1)
                        {
                            objGlTransaction.CREDITAMOUNT_GLT = Convert.ToDecimal(frm["OpenBalance"]);
                            objGlTransaction.DEBITAMOUNT_GLT = 0;
                        }
                        else
                        {
                            objGlTransaction.CREDITAMOUNT_GLT = 0;
                            objGlTransaction.DEBITAMOUNT_GLT = Convert.ToDecimal(frm["OpenBalance"]);
                        }
                        objGlTransaction.NARRATION_GLT = "Opening Balance";
                        objGlTransaction.GLSTATUS_GLT = "OP";
                        _unitOfWork.Repository<GLTRANSACTION1>().Insert(objGlTransaction);
                        _unitOfWork.Save();
                    }
                    success = true;
                    transaction.Commit();
                }
                catch (Exception)
                {
                    success = false;
                    transaction.Rollback();
                }
            }
            return Json(success, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AccountsReceivable()
        {
            ViewBag.Today = today.ToShortDateString();
            return View();
        }

        public ActionResult AccountsPayable()
        {
            ViewBag.Today = today.ToShortDateString();
            return View();
        }

        public ActionResult SaveAccountsPayable()
        {
            throw new NotImplementedException();
        }

        public ActionResult SaveAccountsReceivable()
        {
            throw new NotImplementedException();
        }

        public ActionResult PdcReceipt()
        {
            var objBankTransaction = new BANKTRANSACTION();
            ViewBag.Today = today.ToShortDateString();
            return View(objBankTransaction);
        }

        public ActionResult JvCreation()
        {
            var objBankTransaction = new BANKTRANSACTION();
            ViewBag.Today = today.ToShortDateString();
            return View(objBankTransaction);
        }

        public ActionResult ArapMatching(string AcCode = null, string DocNo = null)
        {
            var objAllocDetails = new ARMATCHING();
            if (!string.IsNullOrEmpty(AcCode))
            {
                var custDetails = (from customers in _unitOfWork.Repository<AR_AP_MASTER>().Query().Get()
                                   where customers.ARCODE_ARM.Equals(AcCode)
                                   select customers).Select(a => new { a.ARCODE_ARM, a.DESCRIPTION_ARM }).FirstOrDefault();
                ViewBag.AcCode = custDetails.ARCODE_ARM;
                ViewBag.AcDesc = custDetails.DESCRIPTION_ARM;
            }
            if (!string.IsNullOrEmpty(DocNo))
            {
                ViewBag.DocNo = DocNo;
            }
            return View(objAllocDetails);
        }

        public ActionResult ArUnmatching()
        {
            ViewBag.DocType = CommonModelAccessUtility.GetDocTypes(_unitOfWork);
            var objAllocDetails = new ARMATCHING();
            return View(objAllocDetails);
        }

        public ActionResult DocumentReversal()
        {
            @ViewBag.DocType = CommonModelAccessUtility.GetDocTypes(_unitOfWork);
            return View();
        }
        public ActionResult DayEndOperation()
        {
            var objDayEnd = new DayEndOperationModel();
            objDayEnd = CommonModelAccessUtility.InitializeDayEndObj(_unitOfWork);
            ViewBag.Today = today.ToShortDateString();
            return View(objDayEnd);
        }
        [HttpPost]
        public JsonResult SavePdcReceipt(FormCollection form, BANKTRANSACTION objBankTransaction)
        {
            string pdcNo = "";
            string currentUser = CommonModelAccessUtility.GetCurrentUser(_unitOfWork);
            bool success;
            using (var transaction = _unitOfWork.BeginTransaction())
            {
                try
                {
                    objBankTransaction.USER_BT = currentUser;
                    objBankTransaction.STATUS_BT = "P";
                    objBankTransaction.MASTERSTATUS_BT = "M";
                    _unitOfWork.Repository<BANKTRANSACTION>().Insert(objBankTransaction);
                    _unitOfWork.Save();
                    _unitOfWork.Truncate("VOUCHERMASTER_RPT");
                    _unitOfWork.Truncate("VOUCHERCHILD_RPT");
                    pdcNo = objBankTransaction.DOCNUMBER_BT;
                    var objVoucherMaster = _unitOfWork.Repository<VOUCHERMASTER_RPT>().Create();
                    objVoucherMaster.GLDATE_VRPT = objBankTransaction.GLDATE_BT;
                    objVoucherMaster.ALLCODE_VRPT = "Bank";
                    objVoucherMaster.BANKCODE_VRT = objBankTransaction.BANKCODE_BT;
                    objVoucherMaster.ACCDESCRIPTION_VRPT = Convert.ToString(form["BankName"]);
                    objVoucherMaster.PARTICULARS_VRPT = objBankTransaction.NARRATION_BT;
                    objVoucherMaster.NOTES_VRPT = objBankTransaction.NOTE_BT;
                    objVoucherMaster.DEBITAMOUT_VRPT = objBankTransaction.DEBITAMOUT_BT;
                    objVoucherMaster.CREDITAMOUNT_VRPT = 0;
                    objVoucherMaster.CHQNO_VRPT = objBankTransaction.CHQNO_BT;
                    objVoucherMaster.CHQDATE_VRPT = objBankTransaction.CHQDATE_BT;
                    objVoucherMaster.DOCNO_VRPT = objBankTransaction.DOCNUMBER_BT;
                    objVoucherMaster.USER_VRPT = currentUser;
                    objVoucherMaster.VOUCHER_TYPE = "BR";
                    _unitOfWork.Repository<VOUCHERMASTER_RPT>().Insert(objVoucherMaster);
                    _unitOfWork.Save();

                    string jsonAllocDetails = form["allocDetails"];
                    var serializer = new JavaScriptSerializer();
                    var lstAllocDetails = serializer.Deserialize<List<CustomAllocationDetails>>(jsonAllocDetails);
                    foreach (var allocDetail in lstAllocDetails)
                    {
                        switch (allocDetail.AlCode)
                        {
                            case "AP":
                                var objApLedger = _unitOfWork.Repository<AR_AP_LEDGER>().Create();
                                objApLedger.DOCNUMBER_ART = objBankTransaction.DOCNUMBER_BT;
                                objApLedger.DODATE_ART = objBankTransaction.DOCDATE_BT;
                                objApLedger.GLDATE_ART = objBankTransaction.GLDATE_BT;
                                objApLedger.ARAPCODE_ART = allocDetail.AccountCode;
                                objApLedger.CREDITAMOUNT_ART = Convert.ToDecimal(allocDetail.Amount);

ASI.MGC.FS/Views/Finance/AccountsPayable.cshtml
@{
    ViewBag.Title = "AccountsPayable";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.currPage = "Accounts Payable";
}
@model ASI.MGC.FS.Model.AR_AP_MASTER
<!-- start:main -->
<div class="container">
    <div id="main">
        <!-- start:breadcrumb -->
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">@ViewBag.currPage</li>
        </ol>
        <!-- end:breadcrumb -->
        <fieldset>
            <legend>Accounts Payable</legend>
            <div class="row">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-11">
                            <div id="grid" class="panel-body">
                                <section>
                                    <button class="btn btn-primary" data-toggle="modal" data-target="#CustomerMasterModel">
                                        Add New Customer
                                    </button>
                                </section>
                                <br /> <br />
                                <section>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <div class="col-md-12 input-group paddingLeftRight0">
                                                @Html.TextBox("searchCustomer", null, new { ID = "txtCustSearch", Class = "form-control" })
                                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <table id="tblCustomerDetails"></table>
                                    <div id="Pager"></div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="container">
    <div class="modal fade" id="CustomerMasterModel" tabindex="-1" role="dialog" aria-labelledby="CustomerMasterModelLabel" aria-hidden="true" data-backdrop="false">
        <div class="modal-dialog modal-lg" style="width: 85%">
            <div class="modal-content">
                @using (Ajax.BeginForm("SaveAccountsPayable", "Finance", null, new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, new { id = "formAccountsPayable", @class = "form-horizontal", enctype = "multipart/form-data" }))
                {
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-hidden="true">
                            ×
                        </button>
                        <h4 class="modal-title">
                            Add Account Payable
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">AP Code</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.ARCODE_ARM, null, new { ID = "txtAPCode", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.ARCODE_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Customer Name</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.DESCRIPTION_ARM, null, new { ID = "txtCustName", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.DESCRIPTION_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">P.O.Box No</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.POBOX_ARM, null, new { ID = "txtPoBox", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.POBOX_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Address 1</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.ADDRESS1_ARM, null, new { ID = "txtAddress1", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.ADDRESS1_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Address 2</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.ADDRESS2_ARM, null, new { ID = "txtAddress2", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.ADDRESS2_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Address 3</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.ADDRESS3_ARM, null, new { ID = "txtAddress3", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.ADDRESS3_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Telephone</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.TELEPHONE_ARM, null, new { ID = "txtTelephone", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.TELEPHONE_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Fax</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.FAX_ARM, null, new { ID = "txtFax", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.FAX_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Email</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.EMAIL_ARM, null, new { ID = "txtEmail", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.EMAIL_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Conatct person:</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.CONDACTPERSON_ARM, null, new { ID = "txtContactPerson", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.CONDACTPERSON_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Sales Exe</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.SALESEXE_ARM, null, new { ID = "txtSaleExe", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.SALESEXE_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Status</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.STATUS_ARM, null, new { ID = "txtStatus", @Value = "Normal", Class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(d => d.STATUS_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Payable Type</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.RECEIVABLETYPE_ARM, null, new { ID = "txtReceiveable", @Value = "Credit", Class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessageFor(d => d.RECEIVABLETYPE_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">GL Date</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("GLDate", null, new { ID = "txtGlDate", @Value = ViewBag.Today, Class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Limit Amount</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.LIMITAMOUNT_ARM, null, new { ID = "txtLimitAmount", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.LIMITAMOUNT_ARM)
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Credit Days</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(d => d.CREDITDAYS_ARM, null, new { ID = "txtCreditDays", Class = "form-control" })
                                    @Html.ValidationMessageFor(d => d.CREDITDAYS_ARM)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Opening Balance</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("OpeningBalance", null, new { ID = "txtOpenBalance", Class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">
                            Save
                        </button>
                        <button type="button" id="btnCancel" class="btn btn-warning">
                            Cancel
                        </button>
                        <button type="button" class="btn btn-default"
                                data-dismiss="modal">
                            Close
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- end:main -->
@section scripts
{
    <script src="@Url.Content("~/Scripts/Custom/Finance/AccountsPayable.js?2500")"></script>
    <script type="text/javascript">

        function OnSuccess(response) {
            alert(response);
            $("#divSaving").hide();
        }

        function OnFailure() {
            alert("Whoops! That didn't go so well did it?");
            $("#divSaving").hide();
        }

    </script>
}

ASI.MGC.FS/Views/Finance/AccountsPayableList.cshtml
@{
    ViewBag.Title = "Accounts Payable";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.currPage = "Accounts Payable";
}
<!-- start:main -->
<div class="container">
    <div id="main">
        <!-- start:breadcrumb -->
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">@ViewBag.currPage</li>
        </ol>
        <!-- end:breadcrumb -->
        <fieldset>
            <legend>Accounts Payable</legend>
            <div class="row">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-11">
                            <div id="grid" class="panel-body">
                                <section>
                                    <div class="row">
                                        <div class="col-md-12 form-group">
                                            <div class="col-md-12 input-group">
                                                @Html.TextBox("accountsPayable", null, new { ID = "txtAccountsPayable", Class = "form-control" })
                                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                            </div>
                                        </div>
                                    </div>
                                    <table id="tblAccountsPayable"></table>
                                    <div id="Pager"></div>
                                </section>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
@section scripts
{
    <script src="@Url.Content("~/Scripts/Custom/Finance/AccountsPayableList.js?2500")"></script>
}

ASI.MGC.FS/Views/Finance/ArUnmatching.cshtml
@{
    ViewBag.Title = "UnMatching";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.currPage = "UnMatching";
}
@model ASI.MGC.FS.Model.ARMATCHING
<link href="~/Content/jquery.jqGrid/ui.jqgrid.css" rel="stylesheet" />
<link href="~/Content/bootstrapValidator.min.css" rel="stylesheet" />
<link href="~/Content/formValidation.min.css" rel="stylesheet" />
<link href="~/Content/Custom/Jquery-ui-modified.min.css" rel="stylesheet" />
<!-- start:main -->
<div class="container">
    <div id="main">
        <!-- start:breadcrumb -->
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">@ViewBag.currPage</li>
        </ol>
        <!-- end:breadcrumb -->
        <fieldset>
            <legend>UnMatching</legend>
            <div class="row">
                <div class="container">
                    @using (Ajax.BeginForm("SaveArUnMatching", "Finance", null, new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, new { id = "formArUnMatching", @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "Required Field", new { @class = "text-danger" })
                    <input id="hdnProductDetails" name="allocDetails" type="hidden" />
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label class="control-label col-md-4 small ">Doc Type:</label>
                            <div class="col-md-8 paddingLeftRight0">
                                @Html.DropDownList("DocType", new SelectList(@ViewBag.DocType, "Key", "Value", "1"), new { ID = "ddlDocType", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-6 form-group">
                            <label id="lblDocNo" class="control-label col-md-4 small ">Invoice Number:</label>
                            <div class="col-md-8 paddingLeftRight0">
                                @Html.TextBoxFor(o => o.DOCCNUMBER_ARM, null, new { ID = "txtInvoiceNumber", Class = "form-control", @required = "required"})
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-10">
                            <fieldset>
                                <legend>UnMatching Details</legend>
                                <div id="grid" class="panel-body">
                                    <section id="unseen">
                                        <table id="tblUnMatchingDetails"></table>
                                    </section>
                                </div>
                            </fieldset>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                        </div>
                        <div class="col-md-6 form-group">
                            <label class="control-label col-md-4 small "></label>
                            <div class="col-md-8 paddingLeftRight0">
                                <input type="submit" class="btn btn-success col-md-3 pull-right" id="btnUnMatch" value="Save">
                                <button type="button" id="btnNew" class="btn btn-success">New</button>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </fieldset>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/Scripts/i18n/grid.locale-en.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrapValidator.min.js")"></script>
    <script src="@Url.Content("~/Scripts/Custom/Finance/ArUnMatching.js?2500")"></script>
    <script src="@Url.Content("~/Scripts/common.js")"></script>
    <script type="text/javascript">

        function OnSuccess(success) {
            if (success) {
                toastr.success("Document unmatched Successfully.");
                $("#btnUnMatch").hide();
            } else {
                toastr.error("Sorry! Something went wrong, please try again.");
            }
            $("#divSaving").hide();
        }

        function OnFailure() {
            toastr.error("Doc Type mismatch or Doc match not found");
            $("#divSaving").hide();
        }

    </script>
}