ASI.MGC.FS/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ASI.MGC.FS.Domain;
using ASI.MGC.FS.ExtendedAPI;
using ASI.MGC.FS.Model;
using ASI.MGC.FS.Models;
using ASI.MGC.FS.WebCommon;

namespace ASI.MGC.FS.Controllers
{
    public class BankController : Controller
    {
        readonly IUnitOfWork _unitOfWork;
        readonly TimeZoneInfo tzInfo;
        DateTime today;
        public BankController()
        {
            _unitOfWork = new UnitOfWork();
            tzInfo = TimeZoneInfo.FindSystemTimeZoneById("Arabian Standard Time");
            today = TimeZoneInfo.ConvertTime(DateTime.Now, tzInfo);
        }
        // GET: Bank
        //public ActionResult Index()
        //{
        //    return View();
        //}
        [MesAuthorize("DailyTransactions")]
        public ActionResult BankReceipt()
        {
            var objBankTransaction = new BANKTRANSACTION();
            @ViewBag.Today = today.ToShortDateString();
            return View(objBankTransaction);
        }
        [MesAuthorize("DailyTransactions")]
        public ActionResult BankPayment()
        {
            var objBankTransaction = new BANKTRANSACTION();
            @ViewBag.Today = today.ToShortDateString();
            return View(objBankTransaction);
        }
        public JsonResult GetBankDetailsList(string sidx, string sord, int page, int rows, string bankName = "")
        {
            var bankList = (from banks in _unitOfWork.Repository<BANKMASTER>().Query().Get()
                            select banks).Select(a => new { a.BANKCODE_BM, a.BANKNAME_BM });
            if (!string.IsNullOrEmpty(bankName))
            {
                bankList = (from banks in _unitOfWork.Repository<BANKMASTER>().Query().Get()
                            where banks.BANKNAME_BM.Contains(bankName)
                            select banks).Select(a => new { a.BANKCODE_BM, a.BANKNAME_BM });
            }
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            int totalRecords = bankList.Count();
            int totalPages = (int)Math.Ceiling(totalRecords / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                bankList = bankList.OrderByDescending(a => a.BANKCODE_BM);
                bankList = bankList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                bankList = bankList.OrderBy(a => a.BANKCODE_BM);
                bankList = bankList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = bankList

            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetBankDetailsByType(string sidx, string sord, int page, int rows, string bankType, string searchById = "", string searchByName = "")
        {
            var bankList = (from banks in _unitOfWork.Repository<BANKMASTER>().Query().Get()
                            select banks).Select(a => new { a.BANKCODE_BM, a.BANKNAME_BM });
            if (!string.IsNullOrEmpty(bankType))
            {
                bankList = (from jobs in _unitOfWork.Repository<BANKMASTER>().Query().Get()
                            where jobs.MODE_BM.Equals(bankType)
                            select jobs).Select(a => new { a.BANKCODE_BM, a.BANKNAME_BM });
            }
            if (!string.IsNullOrEmpty(searchById))
            {
                bankList = bankList.Where(bnk => bnk.BANKCODE_BM.Contains(searchById));
            }
            if (!string.IsNullOrEmpty(searchByName))
            {
                bankList = bankList.Where(bnk => bnk.BANKNAME_BM.Contains(searchByName));
            }
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            int totalRecords = bankList.Count();
            int totalPages = (int)Math.Ceiling(totalRecords / (float)pageSize);
            if (sord.ToUpper() == "DESC")
            {
                bankList = bankList.OrderByDescending(a => a.BANKCODE_BM);
                bankList = bankList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            else
            {
                bankList = bankList.OrderBy(a => a.BANKCODE_BM);
                bankList = bankList.Skip(pageIndex * pageSize).Take(pageSize);
            }
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = bankList

            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveBankReceipt(FormCollection form, BANKTRANSACTION objBankTransaction)
        {
            string brNo = "";
            string currentUser = CommonModelAccessUtility.GetCurrentUser(_unitOfWork);
            using (var transaction = _unitOfWork.BeginTransaction())
            {
                try
                {
                    string docType = form["DocType"];
                    objBankTransaction.DOCNUMBER_BT = CommonModelAccessUtility.GetDocNo(_unitOfWork, docType);
                    objBankTransaction.CREDITAMOUT_BT = 0;
                    objBankTransaction.USER_BT = currentUser;
                    objBankTransaction.STATUS_BT = "P";
                    objBankTransaction.MASTERSTATUS_BT = "M";
                    _unitOfWork.Repository<BANKTRANSACTION>().Insert(objBankTransaction);
                    _unitOfWork.Save();
                    brNo = objBankTransaction.DOCNUMBER_BT;
                    //_unitOfWork.Truncate("VOUCHERMASTER_RPT");
                    //_unitOfWork.Truncate("VOUCHERCHILD_RPT");
                    //var objVoucherMaster = _unitOfWork.Repository<VOUCHERMASTER_RPT>().Create();
                    //objVoucherMaster.GLDATE_VRPT = objBankTransaction.GLDATE_BT;
                    //objVoucherMaster.ALLCODE_VRPT = "Bank";
                    //objVoucherMaster.BANKCODE_VRT = objBankTransaction.BANKCODE_BT;
                    //objVoucherMaster.ACCDESCRIPTION_VRPT = Convert.ToString(form["BankName"]);
                    //objVoucherMaster.PARTICULARS_VRPT = objBankTransaction.NARRATION_BT;
                    //objVoucherMaster.NOTES_VRPT = objBankTransaction.NOTE_BT;
                    //objVoucherMaster.DEBITAMOUT_VRPT = objBankTransaction.DEBITAMOUT_BT;
                    //objVoucherMaster.CREDITAMOUNT_VRPT = 0;
                    //objVoucherMaster.CHQNO_VRPT = objBankTransaction.CHQNO_BT;
                    //objVoucherMaster.CHQDATE_VRPT = objBankTransaction.CHQDATE_BT;
                    //objVoucherMaster.DOCNO_VRPT = objBankTransaction.DOCNUMBER_BT;
                    //objVoucherMaster.USER_VRPT = currentUser;
                    //objVoucherMaster.VOUCHER_TYPE = "BR";
                    //objVoucherMaster.DrawerBr_VRPT = objBankTransaction.BENACCOUNT_BT;
                    //_unitOfWork.Repository<VOUCHERMASTER_RPT>().Insert(objVoucherMaster);
                    //_unitOfWork.Save();

                    string jsonAllocDetails = form["allocDetails"];
                    var serializer = new JavaScriptSerializer();
                    var lstAllocDetails = serializer.Deserialize<List<CustomAllocationDetails>>(jsonAllocDetails);
                    foreach (var allocDetail in lstAllocDetails)
                    {
                        switch (allocDetail.AlCode)
                        {
                            case "AP":
                                var objApLedger = _unitOfWork.Repository<AR_AP_LEDGER>().Create();
                                objApLedger.DOCNUMBER_ART = objBankTransaction.DOCNUMBER_BT;
                                objApLedger.DODATE_ART = objBankTransaction.DOCDATE_BT;
                                objApLedger.GLDATE_ART = objBankTransaction.GLDATE_BT;
                                objApLedger.ARAPCODE_ART = allocDetail.AccountCode;
                                //form["hdnAcCode"] = allocDetail.AccountCode;
                                if (Convert.ToDecimal(allocDetail.Amount) <= 0)
                                {
                                    objApLedger.DEBITAMOUNT_ART = Math.Abs(Convert.ToDecimal(allocDetail.Amount));
                                }
                                else
                                {
                                    objApLedger.CREDITAMOUNT_ART = Math.Abs(Convert.ToDecimal(allocDetail.Amount));
                                }
                                objApLedger.OTHERREF_ART = objBankTransaction.OTHERREF_BT;
                                objApLedger.NARRATION_ART = allocDetail.Narration;
                                objApLedger.MATCHVALUE_AR = 0;
                                objApLedger.USER_ART = currentUser;
                                objApLedger.STATUS_ART = "P";
                                _unitOfWork.Repository<AR_AP_LEDGER>().Insert(objApLedger);
                                _unitOfWork.Save();

                                //var objApVoucherChild = _unitOfWork.Repository<VOUCHERCHILD_RPT>().Create();
                                //objApVoucherChild.ALLCODE_VCD = "GL";
                                //objApVoucherChild.NARRATION_VCD = objBankTransaction.NARRATION_BT;
                                //objApVoucherChild.ACCODE_VCD = allocDetail.AccountCode;
                                //objApVoucherChild.ACDESCRIPTION_VCD = allocDetail.Description;
                                //objApVoucherChild.CREDITAMOUNT_VCD = Convert.ToDecimal(allocDetail.Amount);
                                //objApVoucherChild.AMOUNTSTATUTS_VCD = "Cr";
                                //objApVoucherChild.DOCNO_VCD = objBankTransaction.DOCNUMBER_BT;

ASI.MGC.FS/Views/Bank/BankMaster.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.currPage = "Bank Master";
    ViewBag.Title = "BankMaster";
}
@model ASI.MGC.FS.Model.BANKMASTER
<link href="~/Content/bootstrapValidator.min.css" rel="stylesheet" />
<link href="~/Content/Custom/Jquery-ui-modified.min.css" rel="stylesheet" />
<!-- start:main -->
<div class="container">
    <div id="main">
        <!-- start:breadcrumb -->
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">@ViewBag.currPage</li>
        </ol>
        <!-- end:breadcrumb -->
        <fieldset>
            <legend>Bank Master</legend>
            <div class="row">
                <div class="container">
                    @using (Ajax.BeginForm("SaveBankMaster", "Bank", null, new AjaxOptions { OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, new { id = "formBankMaster", @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "Required Field", new { @class = "text-danger" })
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Bank Code</label>
                                <div class="col-md-8">
                                    <div class="input-group">
                                        @Html.TextBoxFor(o => o.BANKCODE_BM, null, new { ID = "txtBankCode", Class = "form-control", @required = "required" })
                                        <span class="input-group-btn"><button type="button" id="btnBankSearch" class="btn btn-default" data-toggle="modal" data-target="#BankSearchModel"><i class="fa fa-search"></i></button></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Bank Name</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(o => o.BANKNAME_BM, null, new { ID = "txtBankName", Class = "form-control", @required = "required" })
                                    @Html.ValidationMessage("BankName")
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Receipt Loc</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(o => o.RECEIPTLOCATION_BM, null, new { ID = "txtReceiptLoc", Class = "form-control", @Value = "01", @required = "required" })
                                    @Html.ValidationMessage("ReceiptLoc")
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Mode</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.DropDownListFor(o => o.MODE_BM, new SelectList(@ViewBag.bankModeTypes, "Key", "Value", "1"), new { ID = "ddlMode", @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Account No</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(o => o.ACCOUNTNUMBER_BM, null, new { ID = "txtAccNo", Class = "form-control", @required = "required" })
                                    @Html.ValidationMessage("AccNo")
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Currency Code</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(o => o.CURRENCY_BM, null, new { ID = "txtCurrCode", @Value = ViewBag.CurrCode, Class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessage("CurrCode")
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Currency Name</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("CurrName", null, new { ID = "txtCurrName", @Value = ViewBag.CurrName, Class = "form-control", @readonly = "readonly" })
                                    @Html.ValidationMessage("CurrName")
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Bank Status</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.DropDownListFor(o => o.BANKSTTUS_BM, new SelectList(@ViewBag.bankStatus, "Key", "Value", "1"), new { ID = "ddlBankStatus", @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Bank Date</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("BankDate", null, new { ID = "txtBankDate", @Value = ViewBag.Today, Class = "form-control", @required = "required" })
                                    @Html.ValidationMessage("BankDate")
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">Opening Balance</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("OpenBalance", null, new { ID = "txtOpenBalance", Class = "form-control", @required = "required" })
                                    @Html.ValidationMessage("OpenBalance")
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small ">OD Limit</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBoxFor(o => o.ODLIMIT_BM, null, new { ID = "txtODLimit", Class = "form-control", @required = "required" })
                                    @Html.ValidationMessage("ODLimit")
                                </div>
                            </div>
                            <div class="col-md-6 form-group">
                                <label id="lblCustDetail" class="control-label col-md-4 small ">Note (If Any)</label>
                                <div class="col-md-8 paddingLeftRight0">
                                    @Html.TextBox("Note", null, new { ID = "txtNote", Class = "form-control" })
                                    @Html.ValidationMessage("Note")
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 form-group">
                            </div>
                            <div class="col-md-6 form-group">
                                <label class="control-label col-md-4 small "></label>
                                <div class="col-md-8 paddingLeftRight0">
                                    <input type="submit" id="btnSave" class="btn btn-success" value="Save">
                                    <button type="button" id="btnNew" class="btn btn-success">New</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="container">
    <div class="modal fade" id="BankSearchModel" tabindex="-1" role="dialog" aria-labelledby="bankSearchModelLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form class="form-horizontal" id="bankModelform" method="post" data-fv-framework="bootstrap"
                      data-fv-message="This value is not valid"
                      data-fv-feedbackicons-valid="glyphicon glyphicon-ok"
                      data-fv-feedbackicons-invalid="glyphicon glyphicon-remove"
                      data-fv-feedbackicons-validating="glyphicon glyphicon-refresh">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"
                                aria-hidden="true">
                            ×
                        </button>
                        <h4 class="modal-title">
                            Bank Details
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div id="glGrid" class="panel-body">
                                    <div class="col-md-12 form-group">
                                        <div class="col-md-12 input-group paddingLeftRight0">
                                            @Html.TextBox("bankSearch", null, new { ID = "txtBankSearch", Class = "form-control" })
                                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                        </div>
                                    </div>
                                    <br /><br />
                                    <table id="tblBankSearch" style="width: 100%"></table>
                                    <div id="Pager"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">

                        <a href="#" id="btnBankSelect" class="btn btn-success">Select</a>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script src="@Url.Content("~/Scripts/Custom/Bank/BankMaster.js?2500")"></script>
    <script src="@Url.Content("~/Scripts/common.js")"></script>
    <script type="text/javascript">
        var isReportOpened = false;
        function OnSuccess(success) {
            if (success) {
                toastr.success("Bank Details has been added Successfully.");
                $('#formBankMaster')[0].reset();
            } else {
                toastr.error("Sorry! Something went wrong, please try again.");
            }
            $("#divSaving").hide();
        }

        function OnFailure() {
            toastr.error("Sorry! Something went wrong, please try again.");
            $("#divSaving").hide();
        }
    </script>
}